name: crud_firestore
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  animated_loading_bar: ^0.0.3
  another_flushbar: ^1.12.30
  cloud_firestore: ^5.5.0
  connectivity_plus: ^6.1.0
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
